// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagement.Data;

#nullable disable

namespace ProductManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductManagement.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electronic devices and accessories",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Office and stationery items",
                            IsActive = true,
                            Name = "Office Supplies"
                        },
                        new
                        {
                            Id = 3,
                            CreatedUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Home and office furniture",
                            IsActive = true,
                            Name = "Furniture"
                        });
                });

            modelBuilder.Entity("ProductManagement.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ergonomic wireless mouse",
                            IsActive = true,
                            Name = "Wireless Mouse",
                            Price = 19.99m,
                            QuantityInStock = 150,
                            SKU = "ELEC-001"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "RGB backlit mechanical keyboard",
                            IsActive = true,
                            Name = "Mechanical Keyboard",
                            Price = 59.99m,
                            QuantityInStock = 80,
                            SKU = "ELEC-002"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedUtc = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Full HD IPS monitor",
                            IsActive = true,
                            Name = "27-inch Monitor",
                            Price = 179.99m,
                            QuantityInStock = 40,
                            SKU = "ELEC-003"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedUtc = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "500 sheets, 80gsm",
                            IsActive = true,
                            Name = "A4 Paper Ream",
                            Price = 4.99m,
                            QuantityInStock = 500,
                            SKU = "OFF-001"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedUtc = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Pack of 10 blue pens",
                            IsActive = true,
                            Name = "Ballpoint Pen Pack",
                            Price = 3.49m,
                            QuantityInStock = 300,
                            SKU = "OFF-002"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedUtc = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Heavy duty stapler",
                            IsActive = true,
                            Name = "Stapler",
                            Price = 8.99m,
                            QuantityInStock = 120,
                            SKU = "OFF-003"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedUtc = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ergonomic mesh office chair",
                            IsActive = true,
                            Name = "Office Chair",
                            Price = 149.99m,
                            QuantityInStock = 25,
                            SKU = "FURN-001"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedUtc = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Height-adjustable standing desk",
                            IsActive = true,
                            Name = "Standing Desk",
                            Price = 299.99m,
                            QuantityInStock = 15,
                            SKU = "FURN-002"
                        });
                });

            modelBuilder.Entity("ProductManagement.Models.Product", b =>
                {
                    b.HasOne("ProductManagement.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ProductManagement.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
